function init(self)
	print("init menu")
	msg.post(".", "acquire_input_focus")
end

function final(self)
	print("final menu")
	msg.post(".", "release_input_focus")
end


function on_input(self, action_id, action)
	print("on_input menu")
	if(action.pressed) then
		print("action pressed")
	end
	
	if action.pressed and gui.pick_node(gui.get_node("play/bg"), action.x, action.y) then
		print("click play")
		msg.post("controller:/controller", "show_game")
	end
end

